### ISSUE TITLE
Buggy QueryEquivalenceChecker3

### ISSUE THREAD

**Issue by falcaopetri** [lajus/amie#13]
According to `QueryEquivalenceChecker3`, these two rules are equal, i.e., `Rule1.equals(Rule2)` returns `True ` because of `QueryEquivalenceChecker3` :
(I've added `_` to the second one just for alignment purpose)

1. `?e  <rel4>  <const1>  ?e  <rel5>  ?a  ?e  <rel6>  <const3>   => ?a  <rel6>  <const2>`
2. `?e  <rel4>  <const1>  ?e  <rel5>  ?a  __________________    => ?a  <rel6>  <const2>`

Note that `Rule2.equals(Rule1)` returns `False`.

Same for:
3. `?h  <rel1>  <const1>  ?a  <rel1>  <const3>  ?a  <rel2>  ?h   => ?a  <rel3>  <const2>`
4. `?f  <rel1>  <const1>  __________________ ?a  <rel2>  ?f   => ?a  <rel3>  <const2>`

--------------

`bodiesEqual`'s docs says bodies must be the same length, but it doesn't seem to check this. 
It then iterates over the size of the second rule, which might be shorter than the first rule.

https://github.com/lajus/amie/blob/cdb9edad353ea76203d2894d7126160d9feb63d1/rules/src/main/java/amie/rules/QueryEquivalenceChecker3.java#L55-L58

I didn't check any other logic from `QueryEquivalenceChecker3`, but a fix for this specific issue seems to be checking the rules length, which seems to be possible at the beggining of `areEquivalent`, or even at `Rule.equals`.

**Comment by lajus** [comment]
Hi,

We designed the QueryEquivalenceChecker assuming the length test was already done by the calling function. It seems we forgot to verify it was actually the case.

QueryEquivalenceChecker method should indeed be called subsumes() (and can be used for a more general purpose) knowing that if one subsumes the other and both have equal length, then they are equivalent (which is the property we actually use).

Cheers,
Jonathan
