### ISSUE TITLE
Mining with constants crashes

### ISSUE THREAD

**Issue by lgalarra** [lajus/amie#3]
Hi everyone,

When running AMIE 3 with the option "-const" on the YAGO2 sample (http://resources.mpi-inf.mpg.de/yago-naga/amie/data/yago2_sample/yago2core.10kseedsSample.compressed.notypes.tsv), I get the following error:

> java.lang.reflect.InvocationTargetException
> 	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at amie.mining.assistant.MiningAssistant.applyMiningOperators(MiningAssistant.java:1391)
> 	at amie.mining.AMIE$RDFMinerJob.run(AMIE.java:422)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.IllegalArgumentException: The query  => <Australia>  <participatedIn>  ?b does not contain fresh variables in the last triple pattern.
> 	at amie.mining.assistant.MiningAssistant.getInstantiatedAtoms(MiningAssistant.java:793)
> 	... 6 more
> Exception in thread "Thread-2" java.lang.NullPointerException
> 	at amie.mining.AMIE$RDFMinerJob.run(AMIE.java:434)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
>  

This happens with and without multi-threading (-nc 1).

Cheers,
Luis

**Comment by lajus** [comment]
Hi,

I messed up with the concept of open variables with special atoms a while ago (during the typing project I guess). Reverting to the original settings solves the issue (commit 050c0f on master).

Will check if typing is influenced by those changes later.

Cheers,
Jonathan

**Comment by lgalarra** [comment]
So far it seems to work.
