### ISSUE TITLE
Doubt about duplicated rules check

### ISSUE THREAD

**Issue by falcaopetri** [lajus/amie#37]
> **Big disclaimer: I've not profiled or tested any of this. I just had this doubt/idea and would like to share it to check if it makes any sense.**

AMIE paper says that:
> Last, we never enqueue a rule that is already in the queue. **It is expensive to check two rules for equality**. However, **it
is easy to compute measures** such as head coverage, confidence, and PCA confidence for each rule. Two rules can only be equal if they have the same values for these measures. **This restricts the rules that have to be checked**. If a rule is duplicate, we do not enqueue it.

Indeed, when adding the rule to the `AMIEQueue` (a Set), duplicated rules will be ignored based on `Rule.equals`. [`Rule.equals`](https://github.com/lajus/amie/blob/a2beeca2969202602d48f421ba682acc99a02ac2/rules/src/main/java/amie/rules/Rule.java#L1359) first checks the "computed measures" before falling back to "rule equality". 

Suppose that we have `M` enqueued rules and just generated the rule `R`. My question is: _Is computing measures for `R` really faster than computing `M * QueryEquivalenceChecker3.areEquivalent`_?

I understand that there is a combinatorial involved in `QueryEquivalenceChecker3.areEquivalent`, but there is also some cost involved in calculating `R`'s metrics.

My hypothesis (i.e., guess) is that there is a max queue size `N`, such that for `M < N` enqueued rules, it is easier (less computational expensive) to call `QueryEquivalenceChecker3.areEquivalent` `M` times, than to compute the rule's metrics.

Note that this depends on many factors, e.g., how frequently duplicated rules occur, how costly queries are [on average], etc.

> Again, I've got no idea on the costs currently involved in queueing, or whether it is an issue. Table 3 from AMIE+'s paper seems to be related.

Regards,
Antonio.

**Comment by lajus** [comment]
Hi,

To be precise, only the support is computed before the equality check (not the confidence nor the PCA confidence) and is used before testing for equivalency.

AMIE workflow is as follow:

1. Compute the support of any refinement of the rule (using "Count projection bindings" meaning it counts the support of every refinement at the same time, as a SQL query with a GROUP BY clause)
2. For any refinement superior to the support threshold, enqueue it.

Thus, the support is already known when we queue the rule. Note also that in general the support is easier to compute as we count on variables that are already bound together.

For example:
`# x,y : livesIn(x, z) & isLocatedIn(y, z)` is way harder to compute than `# x, y : livesIn(x, y) & isLocatedIn(z, y)` in general.

In practice, (not yet published work) the workflow of AMIE is generally faster than:
```
for rule r:
  for refinement r' of r:
    if r' not in queue:
      compute support of r'
```
Even when the cost of testing if r' is in the queue is 0! This is because with this workflow, we need to compute the support of any refinement independently (on DBPedia 2.0, it takes more than 2 hours).

Cheers,
Jonathan

**Comment by falcaopetri** [comment]
Hi,

Thanks for the reply.

> To be precise, only the support is computed before the equality check (not the confidence nor the PCA confidence) and is used before testing for equivalency.

Indeed, I did not consider this. For some reason, I thought that the `calculateConfidenceMetrics` was being called as soon as we got a candidate rule. Also, as you said, I did not realize that the support is coupled with the refinement (which seems obvious now considering the role of projection queries).

> 1. Compute the support of any refinement of the rule (using "Count projection bindings" meaning **it counts the support of every refinement at the same time**, as a SQL query with a GROUP BY clause)

Just to make it clear for future reference, by "it counts the support of every refinement at the same time,"  you refer to the refinements generated by a specific mining operator. I.e., for each operator `o`, "it counts the support of every refinement `r' ∈ o(r)` at the same time".

Regards,
Antonio.

**Comment by lajus** [comment]
Hi,

> Just to make it clear for future reference, by "it counts the support of every refinement at the same time," you refer to the refinements generated by a specific mining operator. I.e., for each operator o, "it counts the support of every refinement r' ∈ o(r) at the same time".

Exactly, it will compute the support of any refinement with the same shape at the same time. 

For example, for refinements of the rule `livesIn(x, y) & isLocatedIn(z, y)` where `x` and `y` are the head variables, addDanglingAtom will construct the query:
`livesIn(x, y) & isLocatedIn(z, y) & r(x, u)` where `r` is a variable and compute: 
`SELECT r, COUNT(x, y) IN livesIn(x, y) & isLocatedIn(z, y) & r(x, u) GROUP BY r;`

Then it will construct the query: `livesIn(x, y) & isLocatedIn(z, y) & r(u, x)` and compute: 
`SELECT r, COUNT(x, y) IN livesIn(x, y) & isLocatedIn(z, y) & r(u, x) GROUP BY r;`

Then it will construct the query: `livesIn(x, y) & isLocatedIn(z, y) & r(y, u)` and so on.

addClosingAtom will proceed similarly with `livesIn(x, y) & isLocatedIn(z, y) & r(x, z)` 
and `livesIn(x, y) & isLocatedIn(z, y) & r(z, x)`

This is handled by the MiningAssistant and I described here the behaviour of the DefaultMiningAssistant so there might be some minor variations across the different assistants.

Jonathan
