### ISSUE TITLE
Missing dependency (Javatools)

### ISSUE THREAD

**Issue by lgalarra** [lajus/amie#38]
Hi Jonathan,

AMIE's compilation fails in my personal computer where I am compiling it for the first time (by running mvn install). Here is the error message.

[ERROR] Failed to execute goal on project kb: Could not resolve dependencies for project fr.enst.dbweb:kb:jar:1.0: Could not find artifact de.mpg.mpi-inf:javatools:jar:1.0-SNAPSHOT -> [Help 1]

The problem does not happen in my work computer where all dependencies has been fetched before. Maybe is some server  temporarily unavailable?

Cheers,
Luis

**Comment by lajus** [comment]
Reread the instructions on front page.

Jonathan

**Comment by lgalarra** [comment]
Oops.. my mistake, sorry!
