### ISSUE TITLE
Typing module

### ISSUE THREAD

**Issue by lgalarra** [lajus/amie#4]
Hi Jonathan,

I imported AMIE3 using Eclipse but I did not succeed at compiling it at first. The typing module was triggering an error in regards to a dependency in typing/pom.xml. Removing this dependency (starting at line 44) solved the problem:

<dependency>
        <groupId>uk.co.nildram</groupId>
        <artifactId>jsc</artifactId>
        <version>1</version>
</dependency>

Do we really need it? Thanks for your help!

Cheers,
Luis

**Comment by lajus** [comment]
Hi,

I removed the dependency as it is no longer used (and the package seems to be no longer maintained and has been removed from the central repository).

Typing would really need a cleanup as well, when I have the time.

Cheers,
Jonathan
