### ISSUE TITLE
Question - Calculate PCA confidence on new KB

### ISSUE THREAD

**Issue by JohannaJo** [lajus/amie#69]
Hello,
I was wondering if there is some way to use the code in this repo to calculate the PCA confidence of a set of rules (mined with AMIE+) over a new KB?

**Comment by lajus** [comment]
Hello,

I added a script to do just that. If you recompile the project you can call it this way:
```java -cp amie3.jar amie.mining.utils.RecomputeConfidence :tMyOldRuleFile.tsv MyKbFile.tsv```

You can give it multiple KB or rule files, but the rule files must be preceeded by "```:t```".

Regards,

**Comment by JohannaJo** [comment]
Thank you so much for adding this!  

The format for rule file is somewhat unclear to me.
Is it such that for a string rule like this: "?a sibling ?g  ?g sibling ?b => ?a sibling ?b", each space is just replaced by a tab.

Example tsv rule file:
[Test_rules.zip](https://github.com/lajus/amie/files/8022740/Test_rules.zip)
!

**Comment by JohannaJo** [comment]
This is the output I get after running your command with this kb: [win_test_kb.zip](https://github.com/lajus/amie/files/8023844/win_test_kb.zip) and the rules mentioned in the previous comment.
```
Loading files... 
  Starting win_test_kb.tsv
  Finished win_test_kb.tsv, still running: 0
Loaded 88228 facts in 0.83 s using 161 MB
Default mining assistant that defines support by counting support on both head variables
Rule	Head Coverage	Std Confidence	PCA Confidence	Positive Examples	Body size	PCA Body size	Functional variable
Recomputation done in 4 ms
0 rules mined.
```

I have no problem mining rules from the given kb, so I think the problem lies in the formatting or the rules tsv file.
