### ISSUE TITLE
Meaning of terms in the headers of output

### ISSUE THREAD

**Issue by lzzhaha** [lajus/amie#73]
Hi,

I tried the AMIE3 and got some output, but I cannot understand the meaning of some terms in the headers of output. Could you please illustrate what the following terms mean?

- Std Confidence
- Positive Examples
- Body size
- PCA Body size
- Functional variable

Thank you very much.

**Comment by lajus** [comment]
Hi,

- Positive Examples: the support of the rule (number of correct predictions made by the rule).
- Body size: the total number of predictions made by the rule.
- Std Confidence: the confidence under Closed-World Assumption. By definition: std_conf = support / body_size.
- PCA Body Size: the total number of predictions made by the rule under the PCA.
- Functionnal variable: the most functional variable among the variables of the head atom (used for PCA Body Size computation).

If you don't know what I am talking about:
- Check the rule mining section of our [tutorial paper](https://hal.telecom-paris.fr/hal-02302740/file/rw-2019.pdf).
- Check the slides from Fabian Suchanek's course on [rule mining](https://suchanek.name/work/teaching/topics/rule-mining/index.html), more precisely the [one illustrating support and confidence](https://suchanek.name/work/teaching/topics/rule-mining/ilp/index.html#slide-svg-47) and the [one on rule's confidence in KBs](https://suchanek.name/work/teaching/topics/rule-mining/confidence/index.html).
- For PCA, you can also read Luis' [original paper introducing AMIE](https://resources.mpi-inf.mpg.de/yago-naga/amie/amie.pdf).

Cheers,
Jonathan

**Comment by lzzhaha** [comment]
Got it. Thanks.
